# settings config for GamesOnNetworks

use_database = true
use_distributed = true
use_seed = false


[database]
use = "true"
default = "postgres.test" #change this to point towards the database you'd like to use


# sqlite database is provided by default
[database.sqlite]

[database.sqlite.default]
path = "./GamesOnNetworks.sqlite"

# add more sqlite databases below. For example:
# [database.sqlite.my_sqlite_db]
# path = "./my/sqlite/database/path.sqlite"


# postgres database must be configured by the user
[database.postgres]

# configure your own postgres databases below. For example:
# [database.postgres.my_postgres_db]
[database.postgres.test]
user = "postgres"
host = "localhost"
port = "5432"
password = "root"