# settings config for GamesOnNetworks

use_distributed = true
use_seed = false


[databases]
selected = "postgres.test"
# use_store_period = false
# store_period = 0

[databases.sqlite.default]
path = "./GamesOnNetworks.sqlite"

# add more sqlite databases below. For example:
# [databases.sqlite.my_sqlite_db]
# path = "./my/sqlite/database/path.sqlite"


# configure your own postgres databases below. For example:
# [databases.postgres.my_postgres_db]
[databases.postgres.test]
user = "postgres"
host = "localhost"
port = "5432"
password = "root"