# settings config for GamesOnNetworks

use_seed = false
random_seed = 1234
processes = 1

timeout = 3600
#[checkpoint]
#timeout = 3600
#database = ""

figure_dirpath = "" #defined which directory figures should be created in (if relative, relative to project root) #NOTE: could have one of these per database?

# sqlite database is provided by default
[databases]
# use = true
selected = "sqlite.default" #push results to
#query = [] #list of databases to query (must be all sqlite)
checkpoint = true #set true to push the simulation state to the database in the case of a timeout
checkpoint_exit_code = 0 #0 to not exit?
# checkpoint_database = "" #if a main selected database exists and checkpoint is set to true, this database will be used as an alternate for checkpoints (leave empty to use the selected database)
# data_script = "" #supply to initialize database with specific data

[databases.sqlite.default]
path = "GamesOnNetworks.sqlite"

# [databases.sqlite.checkpoint]
# path = "checkpoint.sqlite"

# add more sqlite databases below. For example:
# [databases.sqlite.my_sqlite_db]
# path = "my/sqlite/database/path.sqlite"


# postgres database must be configured by the user
# [databases.postgres.my_postgres_db]

# configure your own postgres databases below. For example:
# [databases.postgres.my_postgres_db]