# settings config for GamesOnNetworks

use_seed = false
processes = 1

# sqlite database is provided by default
[databases]
# use = true
selected = "sqlite.default"

[databases.sqlite.default]
path = "GamesOnNetworks.sqlite"

# add more sqlite databases below. For example:
# [databases.sqlite.my_sqlite_db]
# path = "my/sqlite/database/path.sqlite"


# postgres database must be configured by the user
# [databases.postgres.my_postgres_db]

# configure your own postgres databases below. For example:
# [databases.postgres.my_postgres_db]